sudo: required
dist: trusty
language: node_js
node_js:
 - 6
services:
 - postgresql
postgres:
 adapter: postgresql
 database: doc-mgt-test
 username: postgres
before_script:
  - psql -c 'create database travis;' -U postgres
  - dropdb --if-exists travis && createdb travis
  - npm install
  - sequelize db:migrate
after_success:
  - npm run coverage
after_failure:
  - npm run coverage
script:
  - npm test